### ISSUE TITLE
Display address above flag banner

### ISSUE THREAD

**Issue by mapomatic** [WazeUSA/WME-Place-Harmonizer#113] opened 2017-01-29 19:43 UTC
Use this space to display the address, and maybe even a button that will take you to the address editing area and automatically open it.  Should probably be a configurable option.

![image](https://cloud.githubusercontent.com/assets/19505091/22407273/37edf616-e631-11e6-9b49-faa46e5d6eab.png)

**Comment by helifino** [comment] 2017-02-04 07:27
Duplicate of #75

**Closed** 2017-02-13 21:27 UTC
Labels: Duplicate

**Comment by mapomatic** [comment] 2017-05-25 19:18
@justins83 will add a feature to PIE that will move the address to the top (not above the banner, but probably to the top of the edit tab).
